config/routes.rb
Rails.application.routes.draw do
  get 'supplier_lists/index'
  devise_for :users, controllers: {registrations: 'users'}
  get 'outlet_lists/index'
  get 'storehouses/index'
  get 'storehouses/show'
  get 'storehouses/new'
  get 'storehouses/edit'
  get 'storehouse/index'
  get 'storehouse/show'
  get 'storehouse/new'
  get 'storehouse/edit'
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'orders/edit'
  get 'outlets/index'
  get 'outlets/show'
  get 'outlets/new'
  get 'outlets/edit'
  get 'emails/index'
  get 'phones/index'
  get 'users/index'
  get 'addresses/index'
  get 'cities/index'
  get 'roles/index'
  get 'suppliers/index'
  get 'technics/index'
  get 'folks/index'
  get 'keyboards/index'
  get 'drums/index'
  get 'winds/index'
  get 'boweds/index'
  get 'categories/index'
  get 'guitars/index'
  get 'welcome/index'

  resources :products do
  	resources :product_attrs
  end

	resources :guitars
	resources :categories
	resources :boweds
	resources :winds
	resources :drums
	resources :keyboards
	resources :folks
	resources :technics
  
	resources :suppliers do
    resources :supplier_lists
  end
	resources :roles
  resources :cities
  resources :addresses
  resources :users
  resources :phones
  resources :emails

  resources :outlets do
    resources :outlet_lists
  end
  
  resources :orders do
    resources :order_lists
  end
  
  resources :storehouses
	root 'welcome#index', as: "home"
	
end

app/models/address.rb
class Address < ApplicationRecord
	has_one :user

	validates :address, presence: true,
                    length: { minimum: 2 }

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product
	validates :title, presence: true,
                    length: { minimum: 4 }
end

app/models/email.rb
class Email < ApplicationRecord
	validates :email, presence: true,
                    length: { minimum: 6 }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_lists

  validates :status, presence: true,
                    length: { minimum: 2 }
end

app/models/order_list.rb
class OrderList < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/outlet.rb
class Outlet < ApplicationRecord
	has_many :outlet_lists

	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/outlet_list.rb
class OutletList < ApplicationRecord
  belongs_to :outlet
  belongs_to :product
end

app/models/phone.rb
class Phone < ApplicationRecord
	belongs_to :user

		validates :phone, presence: true,
                    length: { minimum: 7 }
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :category
	has_many :supplier_lists
	has_many :outlet_lists
	has_many :storehouses
	has_many :product_attrs, dependent: :destroy
	has_many :order_lists
	validates :title, presence: true,
                    length: { minimum: 2 }
    validates :status, presence: true
end

app/models/product_attr.rb
class ProductAttr < ApplicationRecord
  belongs_to :product
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users

	validates :title, presence: true,
                    length: { minimum: 4 }
end

app/models/storehouse.rb
class Storehouse < ApplicationRecord
  belongs_to :product
  validates :count, presence: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
	has_many :supplier_lists, dependent: :destroy

	validates :title, presence: true,
                    length: { minimum: 4 }
end

app/models/supplier_list.rb
class SupplierList < ApplicationRecord
  belongs_to :product
  belongs_to :supplier
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
         
	has_many :phones 
	has_many :orders
	has_many :emails
	belongs_to :role
	belongs_to :address
	
	accepts_nested_attributes_for :address, allow_destroy: true


	validates :title, presence: true
                    
end

app/controllers/storehouses_controller.rb
class StorehousesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
 def index
    @storehouses = Storehouse.all
  end

  def show
    @storehouse = Storehouse.find(params[:id])
  end

  def new
    @storehouse = Storehouse.new
  end

  def edit
    @storehouse = Storehouse.find(params[:id])
  end

  def create
  @storehouse = Storehouse.new(storehouse_params)
  
  if @storehouse.save
      redirect_to @storehouse
  else
    render 'new'
  end
  end

  def update
    @storehouse = Storehouse.find(params[:id])

    if @storehouse.update(storehouse_params)
      redirect_to @storehouse
    else
      render 'edit'
    end
  end

  def destroy
    @storehouse = Storehouse.find(params[:id])
    @storehouse.destroy

    redirect_to storehouses_path
end

  private
    def storehouse_params
      params.require(:storehouse).permit(:count, :product_id)
  end
end

app/helpers/drums_helper.rb
module DrumsHelper
end

app/helpers/folks_helper.rb
module FolksHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/storehouses_helper.rb
module StorehousesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/winds_helper.rb
module WindsHelper
end

app/views/storehouses/edit.html.erb
<h1>Storehouses#edit</h1>
<p>Find me in app/views/storehouses/edit.html.erb</p>

app/views/storehouses/index.html.erb
<%= link_to 'Добаить товар', new_storehouse_path, class: 'btn btn-success' %><br>
<h1>Склад</h1>
            <h5>Список товаров на складе:</h5>
<table>
    <tr>
        <th>Название</th>
        <th></th>
    </tr>
    <% @storehouses.each do |store| %>
    <tr class="list">
        <td>
            <%# @storehouses.each do |list| %>
            <div>
                <%= Product.where(:id => store.product_id).pluck(:title).first%> --
                <%= Category.joins(:product).where(products: {:id => store.product_id}).pluck(:title).first%>
            </div>
            <% #end %>
        </td>
        <!--         <td>
            <%= link_to 'Просмотр', storehouse_path(store),class: "btn btn-secondary btn-sm" %>
        </td> -->
<!--         <td>
            <%= link_to 'Изменить', edit_storehouse_path(store),class: "btn btn-secondary btn-sm" %>
        </td>
        <td>
            <%= link_to 'Удалить', storehouse_path(store),class: "btn btn-secondary btn-sm",
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
        </td> -->
    </tr>
    <% end %>
</table>

app/views/storehouses/new.html.erb
<h1>Новый инструмент</h1>

<%= form_with scope: :storehouse, url:storehouses_path,local: true do |form| %>

  <% if @storehouse.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@storehouse.errors.count, "error") %> prohibited
        this storehouse from being saved:
      </h2>
      <ul>
        <% @storehouse.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= form.label :Инструмент%></strong><br>
        <%= form.collection_select :product_id, Product.where(status: 'Supplier').order(:title), :id,:title, class: 'form-control' %>
        <br>
    <%= form.label :Количество %><br>
    <%= form.text_field :count, class: 'form-control' %>

    
  </div>
<br>
  <div class="form-group">
    <%= form.submit 'Добавить', class: 'btn btn-primary' %>
    <%= link_to 'Назад', storehouses_path, class: 'btn btn-outline-secondary' %>
  </div>

<% end %>

app/views/storehouses/show.html.erb
<p>
    Инструмент добавлен.
</p>
<%= link_to 'Назад', storehouses_path, class: 'btn btn-outline-secondary' %>