config/routes.rb
Rails.application.routes.draw do
  get 'supplier_lists/index'
  devise_for :users, controllers: {registrations: 'users'}
  get 'outlet_lists/index'
  get 'storehouses/index'
  get 'storehouses/show'
  get 'storehouses/new'
  get 'storehouses/edit'
  get 'storehouse/index'
  get 'storehouse/show'
  get 'storehouse/new'
  get 'storehouse/edit'
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'orders/edit'
  get 'outlets/index'
  get 'outlets/show'
  get 'outlets/new'
  get 'outlets/edit'
  get 'emails/index'
  get 'phones/index'
  get 'users/index'
  get 'addresses/index'
  get 'cities/index'
  get 'roles/index'
  get 'suppliers/index'
  get 'technics/index'
  get 'folks/index'
  get 'keyboards/index'
  get 'drums/index'
  get 'winds/index'
  get 'boweds/index'
  get 'categories/index'
  get 'guitars/index'
  get 'welcome/index'

  resources :products do
  	resources :product_attrs
  end

	resources :guitars
	resources :categories
	resources :boweds
	resources :winds
	resources :drums
	resources :keyboards
	resources :folks
	resources :technics
  
	resources :suppliers do
    resources :supplier_lists
  end
	resources :roles
  resources :cities
  resources :addresses
  resources :users
  resources :phones
  resources :emails

  resources :outlets do
    resources :outlet_lists
  end
  
  resources :orders do
    resources :order_lists
  end
  
  resources :storehouses
	root 'welcome#index', as: "home"
	
end

app/models/address.rb
class Address < ApplicationRecord
	has_one :user

	validates :address, presence: true,
                    length: { minimum: 2 }

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product
	validates :title, presence: true,
                    length: { minimum: 4 }
end

app/models/email.rb
class Email < ApplicationRecord
	validates :email, presence: true,
                    length: { minimum: 6 }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_lists

  validates :status, presence: true,
                    length: { minimum: 2 }
end

app/models/order_list.rb
class OrderList < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/outlet.rb
class Outlet < ApplicationRecord
	has_many :outlet_lists

	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/outlet_list.rb
class OutletList < ApplicationRecord
  belongs_to :outlet
  belongs_to :product
end

app/models/phone.rb
class Phone < ApplicationRecord
	belongs_to :user

		validates :phone, presence: true,
                    length: { minimum: 7 }
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :category
	has_many :supplier_lists
	has_many :outlet_lists
	has_many :storehouses
	has_many :product_attrs, dependent: :destroy
	has_many :order_lists
	validates :title, presence: true,
                    length: { minimum: 2 }
    validates :status, presence: true
end

app/models/product_attr.rb
class ProductAttr < ApplicationRecord
  belongs_to :product
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users

	validates :title, presence: true,
                    length: { minimum: 4 }
end

app/models/storehouse.rb
class Storehouse < ApplicationRecord
  belongs_to :product
  validates :count, presence: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
	has_many :supplier_lists, dependent: :destroy

	validates :title, presence: true,
                    length: { minimum: 4 }
end

app/models/supplier_list.rb
class SupplierList < ApplicationRecord
  belongs_to :product
  belongs_to :supplier
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
         
	has_many :phones 
	has_many :orders
	has_many :emails
	belongs_to :role
	belongs_to :address
	
	accepts_nested_attributes_for :address, allow_destroy: true


	validates :title, presence: true
                    
end

app/controllers/guitars_controller.rb
class GuitarsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
  def index
  	@guitars = Product.joins(:category).where(categories: {title: 'guitar'})
  end

  def show
  	@product = Product.find(params[:id])
  end


  def instruments
    @guitars = Product.all.where(type: 'guitar')
  end


end

app/helpers/drums_helper.rb
module DrumsHelper
end

app/helpers/folks_helper.rb
module FolksHelper
end

app/helpers/guitars_helper.rb
module GuitarsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/winds_helper.rb
module WindsHelper
end

app/views/guitars/_guitar.html.erb
<article clsas="post">
	<section class="post-head">
    <h2><%= link_to @guitar.title, guitar_path(@guitar) %></h2>
    <small>
      <time><%= @guitar.created_at.to_date.strftime("%d %B, %Y") %></time>
        |
        <%= link_to 'Изменить', edit_guitar_path(@guitar) %>
        |
        <%= link_to 'Удалить', guitar_path(@guitar), method: :delete, data: { confirm: 'Вы уверены?' } %>

    </small>
  </section>
</article>

app/views/guitars/index.html.erb
<% @guitars.each do |guitar| %>
<tr>
    <td>
      <article class="post">
        <h2><%= link_to guitar.title, guitar_path(guitar) %></h2>
        <small>
            <time>
                <%= guitar.created_at.to_date.strftime("%d %B, %Y") %></time>
                <% if user_signed_in?%>
            |
            <%= link_to 'Изменить', edit_guitar_path(guitar) %>
            |
            <%= link_to 'Удалить', guitar_path(guitar), method: :delete, data: { confirm: 'Вы уверены?' } %>
            <% end%>
        </small>
      </article>
    </td>
</tr>
<br>
<% end %>
<!--  
<hr color="#92e5f7">
<div class="tableg">
    <div class="tbodyg">
        <div class="rowg">
            <div class="cellg">
                <%= image_tag("guitars.jpg",:alt =>"guitars",style:'height:15vw;width:17vw;')%><br>
                гитары</div>
            <div class="cellg">
                <%= image_tag("plasters1.jpg",:alt =>"accessories",style:'height:15vw;width:17vw;')%><br>
                аксессуары</div>
        </div>
        <div class="rowg">
            <div class="cellg">
                <%= image_tag("strings1.jpg",:alt =>"strings",style:'height:15vw;width:17vw;')%><br>
                струны</div>
            <div class="cellg">
                <%= image_tag("pedals.jpg",:alt =>"pedals",style:'height:15vw;width:17vw;')%><br>
                педали</div>
        </div>
    </div>
</div>
<hr color="#92e5f7">



<br>
<hr color="#92e5f7">
<%= link_to 'Главная', controller: 'welcome' %>-->

app/views/guitars/instruments.html.erb
  <% @guitars.each do |guitar| %>
    <tr>
      <td><%= guitar.title %></td>
      <td><%= link_to 'Show', guitar_path(guitar) %></td>
    </tr>
    <br>
  <% end %>

app/views/guitars/show.html.erb
<p>
  <strong>Название:</strong>
  <%= @product.title %>
</p>

<strong>Характеристики:</strong><br>
<% @product.product_attrs.each do |attrv| %>
  <%= attrv.title %>:   <%= attrv.value %><br>  
<% end %>


<hr>
<%= link_to 'Назад', guitars_path, class: 'btn btn-outline-secondary' %>